CREATE DATABASE DBRanking;
USE DBRanking;
CREATE TABLE ESCOLA (
ID_ESC INT PRIMARY KEY,
RANK_ESC INT NOT NULL,
NOME_ESC VARCHAR(100)NOT NULL,
MED_INI DECIMAL(2,2),
MED_FIN DECIMAL(2,2),
MED_MED DECIMAL(2,2),
MED_IDEB DECIMAL(2,2)
);