/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package framesPackage;

import connectionsPackage.AlunoDAO;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Will
 */
public class FrameMenu extends javax.swing.JFrame {
    public static String ra,nome;
    /**
     * Creates new form FrameMenu
     */
    public FrameMenu(String ra) {
        initComponents();
        this.ra = ra;
        AlunoDAO alunoDAO = new AlunoDAO();
        nome = alunoDAO.getNome(ra);
        labelNome.setText("Olá " + nome);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frameMenu = new javax.swing.JPanel();
        btnRanking = new javax.swing.JButton();
        btnSugestao = new javax.swing.JButton();
        labelNome = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");

        frameMenu.setBackground(new java.awt.Color(204, 255, 255));

        btnRanking.setText("Ranking de escolas");
        btnRanking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnRankingMousePressed(evt);
            }
        });

        btnSugestao.setText("Dê uma sugestão");
        btnSugestao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSugestaoMousePressed(evt);
            }
        });

        labelNome.setForeground(new java.awt.Color(0, 0, 255));
        labelNome.setText("/nome do aluno");

        btnSair.setText("Sair");
        btnSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSairMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout frameMenuLayout = new javax.swing.GroupLayout(frameMenu);
        frameMenu.setLayout(frameMenuLayout);
        frameMenuLayout.setHorizontalGroup(
            frameMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frameMenuLayout.createSequentialGroup()
                .addContainerGap(128, Short.MAX_VALUE)
                .addGroup(frameMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frameMenuLayout.createSequentialGroup()
                        .addGroup(frameMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnRanking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSugestao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(131, 131, 131))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frameMenuLayout.createSequentialGroup()
                        .addComponent(labelNome)
                        .addGap(156, 156, 156))))
            .addGroup(frameMenuLayout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        frameMenuLayout.setVerticalGroup(
            frameMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelNome)
                .addGap(60, 60, 60)
                .addComponent(btnRanking)
                .addGap(18, 18, 18)
                .addComponent(btnSugestao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(btnSair)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(frameMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(frameMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMouseClicked
        FrameLogin frl = new FrameLogin();
        frl.setLocationRelativeTo(null);
        frl.setVisible(true);
        FrameMenu.this.dispose();
    }//GEN-LAST:event_btnSairMouseClicked

    private void btnRankingMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRankingMousePressed
        FrameRanking frk;
        try {
            frk = new FrameRanking(ra);
            frk.setLocationRelativeTo(null);
            frk.setVisible(true);
            FrameMenu.this.dispose();

        } catch (Exception ex) {
            Logger.getLogger(FrameMenu.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnRankingMousePressed

    private void btnSugestaoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSugestaoMousePressed
        FrameSugestao frs = new FrameSugestao(ra);
        frs.setLocationRelativeTo(null);
        frs.setVisible(true);
        FrameMenu.this.dispose();
    }//GEN-LAST:event_btnSugestaoMousePressed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRanking;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSugestao;
    private javax.swing.JPanel frameMenu;
    private javax.swing.JLabel labelNome;
    // End of variables declaration//GEN-END:variables
}
